#!/bin/bash

set -ex

# VARIABLES
FTP_ADM_USER=${FTP_ADM_USER:-"ftpadm"}
FTP_ADM_PASS=${FTP_ADM_PASS:-"1qaz@WSX"}

# SIGTERM handler
function _term() {

   echo "Stopping container."
   echo "SIGTERM received, shutting down the server!"
   kill -15 $childPID
   exit 0 # 128+15

}

# SIGKILL handler
function _kill() {

   echo "SIGKILL received, shutting down the server!"
   kill -9 $childPID
   # exit 137 # 128+9

}

# Set SIGTERM handler
trap _term SIGTERM

# Set SIGKILL handler
trap _kill SIGKILL

echo "Adding user ${FTP_ADM_USER}"
useradd -c "ftp user" -s /sbin/nologin "${FTP_USER}"
echo -e "${FTP_PASSWORD}" | passwd ${FTP_USER}
echo "${FTP_USER}" >> /etc/vsftpd/user_list

while read -r user; do
    IFS=: read -r FTP_USER FTP_PASSWORD <<< "${!user}"
    echo "Adding user ${FTP_USER}"
    useradd -c "ftp user" -s /sbin/nologin "${FTP_USER}"
    echo -e "${FTP_PASSWORD}" | passwd ${FTP_USER}
    echo "${FTP_USER}" >> /etc/vsftpd/user_list
done < <(env | grep "FTP_USER_" | sed 's/^\(FTP_USER_[a-zA-Z0-9]*\)=.*/\1/')

ln -sf /dev/stdout /var/log/xferlog

vsftpd /etc/vsftpd/vsftpd.conf &

childPID=$!
wait $childPID
